### ISSUE TITLE
Relatório de todas as demandas por cliente #24

### ISSUE THREAD

**Issue by laispa** [Siged-Gces-2023-2/2023.2-SIGeD-GCES-Doc#5]
Descrição
Atualmente no sistema SIGED é permitida a impressão de uma demanda por vez para um determinado cliente. Entretanto, podemos ter para um mesmo cliente, várias demandas e para imprimir todas as demandas de um determinado cliente deve-se fazer a impressão de cada demanda associada ao cliente.

Objetivo
Permitir a impressão de todas as demandas de um determinado cliente. Ao listar o prontuário do cliente com as demandas criadas seja apresentado um botão para impressão de todas as demandas agrupadas para aquele cliente

**Comment by DaviSilva25** [comment]
Issue fechada com o merge do PR: https://github.com/DITGO/2021-2-SiGeD-Frontend/pull/24
