### ISSUE TITLE
Impressão de Relatório de Demandas na Tela de Perfil do Cliente

### ISSUE THREAD

**Issue by luclopesr** [Siged-Gces-2023-2/2023.2-SIGeD-GCES-Doc#9]
**Descrição**
Atualmente, na tela de Perfil do Cliente, não é permitido a impressão de relatório de demandas, seja em conjunto ou individual. Entretanto, podemos ter várias demandas para um mesmo cliente.

**Objetivo**
- Na tela de Perfil do Cliente, permitir a impressão do relatório de todas as demandas de um determinado cliente.
- Na tela de Perfil do Cliente, permitir a impressão do relatório de uma demanda individualmente.

A imagem a seguir demonstra as implementações necessárias:
![photo_2023-10-18_10-55-12](https://github.com/DITGO/2021-2-SiGeD-Doc/assets/88348202/fae8a11c-aab1-4b04-8488-5a192968c4e7)

**Tarefas**
- [x]  Ao listar o prontuário do cliente com as demandas criadas seja apresentado um botão para impressão de todas as demandas agrupadas para aquele cliente.
- [x] Ao listar o prontuário do cliente com as demandas criadas seja apresentado um botão em cada uma das demandas para impressão do relatório individual de demanda.

**Checklist**
- [x] A issue possui nome significativo.
- [x] A issue possui descrição significativa.
- [x] A issue possui screenshots quando necessárias.
- [x] A issue possui labels.

**Comment by DaviSilva25** [comment]
Issue concluída com o merge do PR: https://github.com/DITGO/2021-2-SiGeD-Frontend/pull/24
